botsite/urls.py
from django.urls import path

from botsite import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('test/', views.test, name='test'),
    # path('conversations/<int:conversation>/random_post/', views.random_post, name='random_post'),
    # path('conversations/<int:pk>/random_post/', views.ChatSettingUpdate.as_view(), name='random_post'),
    path('account_creation_info/', views.account_creation_info, name='account_creation_info'),
    path('conversations/<int:conversation>/', views.conversation_settings, name='bot_settings'),




]

vk/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('vkreceiver/', views.vkreceiver, name='vkreceiver'),
    path('capacity/', views.capacity_test),
    path('capacity2/', views.capacity_test2),
    path('celery_test/', views.celery_test),
    path('celery_test2/', views.celery_test2),



]

botsite/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    """ CharFields and TextFields are never saved as NULL in Django . Blank values are stored in the DB as an empty string ('').
     So null=True is unnecessary.
     However, you can manually set one of these fields to None to force set it as NULL.
     If you have a scenario where that might be necessary, you should still include null=True."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    vk_id = models.BigIntegerField(unique=True)
    vk_token = models.CharField(max_length=200, blank=True)

vk/models.py
from django.db import models
from django.utils import timezone

from vk.helpers import five_minutes_ago


class Chat(models.Model):
    chat_id = models.BigIntegerField(primary_key=True)
    local_id = models.BigIntegerField(blank=True, null=True)
    title = models.CharField(max_length=110, blank=True, null=True)
    members_count = models.IntegerField(blank=True, null=True)
    owner_id = models.BigIntegerField(db_index=True)
    conversation_is_registered = models.BooleanField(default=False)

    smart_mode = models.BooleanField(default=False)

    interval_mode = models.BooleanField(default=False)
    interval = models.PositiveIntegerField(blank=True, null=True)
    messages_till_endpoint = models.PositiveIntegerField(blank=True, null=True)  # includes zero

    first_contact = models.DateTimeField(default=timezone.now)
    last_contact = models.DateTimeField(default=timezone.now)


class ChatMessage(models.Model):
    text = models.TextField(blank=True)
    chat_id = models.ForeignKey(
        Chat, on_delete=models.CASCADE)
    from_user_id = models.BigIntegerField()
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.text)


class UserMessage(models.Model):
    text = models.TextField(blank=True)
    from_id = models.BigIntegerField()
    time = models.DateTimeField(default=timezone.now)


class IntervalPhrase(models.Model):
    id = models.AutoField(primary_key=True)
    chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
    phrase = models.CharField(max_length=4000)


class SmartReply(models.Model):
    id = models.AutoField(primary_key=True)
    chat_id = models.ForeignKey(Chat, on_delete=models.CASCADE)
    trigger = models.CharField(max_length=100)
    reply = models.CharField(max_length=100)
    last_used = models.DateTimeField(default=five_minutes_ago, blank=True)
    regex = models.BooleanField(default=False)


class NewPostSetting(models.Model):
    chat_id = models.OneToOneField(
        Chat, on_delete=models.CASCADE, primary_key=True)
    newpost_mode = models.BooleanField(default=False)
    newpost_group_link = models.CharField(max_length=200, blank=True)
    # TODO group address validator
    newpost_group_id = models.BigIntegerField(blank=True, null=True)
    latest_newpost_timestamp = models.BigIntegerField(default=0)


class KickNonMembersSetting(models.Model):
    chat_id = models.OneToOneField(
        Chat, on_delete=models.CASCADE, primary_key=True)
    kick_nonmembers_mode = models.BooleanField(default=False)
    kick_nonmembers_group_link = models.CharField(max_length=200, blank=True)
    # TODO group address validator
    kick_nonmembers_group_id = models.BigIntegerField(blank=True, null=True)


class RandomPostSetting(models.Model):
    chat_id = models.OneToOneField(
        Chat, on_delete=models.CASCADE, primary_key=True)
    random_post_mode = models.BooleanField(default=False)
    random_post_group_link = models.CharField(max_length=200, blank=True, )
    # TODO group address validator
    random_post_group_id = models.BigIntegerField(blank=True, null=True)

botsite/forms.py
from django.forms import ModelForm
from vk.models import *


# class ChatSettingForm(ModelForm):
#     class Meta:
#         model = ChatSetting
#         fields = ['random_post_group']
#
#
# class ChatConversationForm(ModelForm):
#     class Meta:
#         model = ChatConversation
#         fields = ['random_post_mode']

botsite/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import UpdateView
from django.contrib import messages

# from botsite.forms import ChatConversationForm, ChatSettingForm
from botsite.models import UserProfile
# from vk.models import ChatConversation, ChatSetting
from vk.models import Chat, RandomPostSetting


def home(request):
    return render(request, "botsite/home.html")


@login_required
def profile(request):
    current_user = User.objects.get(username=request.user)
    idVK = UserProfile.objects.get(user_id=current_user.id).vk_id
    conversations = Chat.objects.filter(owner_id=idVK)
    context = {'conversations': conversations}
#TODO: делать запрос в контакт и получать имя чата
    return render(request, "botsite/profile.html", context)


def account_creation_info(request):
    return render(request, "botsite/account_creation_info.html")


def test(request):
    return render(request, "botsite/test.html")


# class ChatSettingUpdate(UpdateView):
#     model = ChatSetting
#     fields = ['random_post_group']
#     template_name = "botsite/random_post.html"

# def get_context_data(self, **kwargs):
#         context = super(TaffyUpdateView, self).get_context_data(**kwargs)
#         context['second_model'] = SecondModel.objects.get(id=1) #whatever you would like
#         return context

# def get_context_data(self, **kwargs):
#     context = super(ChatSettingUpdate, self).get_context_data(**kwargs)
#     # {'object': <ChatSetting: 2000000005>, 'chatsetting': <ChatSetting: 2000000005>,
#     # 'form': <ChatSettingForm bound=False, valid=Unknown, fields=(random_post_group)>, 'view': <botsite.views.ChatSettingUpdate object at 0x000002078FC7AE48>}
#     # print(self.kwargs['pk'])
#     chat_conversation_object = ChatConversation.objects.get(peer_id=self.kwargs['pk'])
#     context['chat_conversation'] = {'object': chat_conversation_object, 'form': ChatConversationForm}
#     print(context)
#     return context

# def get_success_url(self):
#     messages.add_message(self.request, messages.INFO, 'form submission success')
#     return self.request.path


# @login_required
# def random_post(request, conversation):
#     chat_setting_instance = get_object_or_404(RandomPostSetting, peer_id=conversation)
#     chat_conversation_instance = get_object_or_404(Chat, peer_id=conversation)
#
#     if request.method == 'POST':
#         chat_setting_form = ChatSettingForm(request.POST, instance=chat_setting_instance)
#         chat_conversation_form = ChatConversationForm(request.POST, instance=chat_conversation_instance)
#
#         if chat_setting_form.is_valid() and chat_conversation_form.is_valid():
#             print("in view:", chat_setting_form['random_post_group'].value())
#
#             chat_setting_form.save()
#             chat_conversation_form.save()
#
#             return redirect(request.path)
#         else:
#             context = {
#                 'chat_setting_form': chat_setting_form,
#                 'chat_conversation_form': chat_conversation_form,
#             }
#             return render(request, "botsite/random_post.html", context)
#
#
#
#     else:
#         chat_setting_instance = get_object_or_404(ChatSetting, peer_id=conversation)
#         chat_conversation_instance = get_object_or_404(ChatConversation, peer_id=conversation)
#
#         chat_setting_form = ChatSettingForm(instance=chat_setting_instance)
#         chat_conversation_form = ChatConversationForm(instance=chat_conversation_instance)
#
#         context = {
#             'chat_setting_form': chat_setting_form,
#             'chat_conversation_form': chat_conversation_form,
#         }
#
#         return render(request, "botsite/random_post.html", context)



@login_required
def conversation_settings(request, conversation):
    # check for user and conversation
    return render(request, "botsite/bot_settings.html")


def error_500(request, *args):
    return render(request, 'botsite/500.html', status=500)


def error_404(request, exception):
    return render(request, 'botsite/404.html', status=404)

botsite/templates/botsite/account_creation_info.html
{% extends 'botsite/base.html' %}

{% block Title %}Home{% endblock %}
{% block Content %}

<div class="container main-content">
<p>
Здесь будет информация о том, как создать учетную запись.
    </p> </div>

{% endblock %}

botsite/templates/botsite/base.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link href="{% static 'botsite/css/base.css' %}" rel="stylesheet">


    <title>{% block Title %}VKBot{% endblock %}</title>
</head>
<body class="text-center">
<header>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top " style="background-color: #989ea4">
        <a class="navbar-brand mr-auto" href="{% url 'home' %}">VKBot</a>




        <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse  flex-grow-0 " id="navbarSupportedContent">



            <ul class="navbar-nav text-right ">
                {% block Menu %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'profile' %}">Личный кабинет</a>

                </li>
                <li class="nav-item active">
                    {% if user.is_authenticated %}

                    <a href="{% url 'logout' %}" class="nav-link ml-auto mr-1"
                       style="color: #fdfafc !important;">Выйти</a>
                    {% else %}
                    <a href="{% url 'vk_auth' %}" class="nav-link ml-auto mr-1"
                       style="color: #fdfafc !important;">Войти</a>
                    {% endif %}
                </li>
            {% endblock %}
            </ul>

        </div>


    </nav>


</header>

<main>

    {% block Content %}
    {% endblock %}

</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>
</html>

botsite/templates/botsite/bot_settings.html
{% extends 'botsite/base.html' %}
{% load static %}


{% block Title %}Settings{% endblock %}

{% block Content %}


<link href="{% static 'botsite/css/bot_settings.css' %}" rel="stylesheet">

<div class="container main-content center-content ">

    <div class="card " style="margin-bottom:5px;">

  <div class="card-body d-flex align-items-center " >
      <a class=" btn  shadow-none  h-100 mask btn-block" href="{% url 'random_post' conversation=request.resolver_match.kwargs.conversation  %}" style="text-align:center; " role="button"> <h3> Настройка функции "Случайный пост" </h3> </a>
       <span class="vertical-line"></span>
      <button class="btn btn-link shadow-none" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="text-align:center; ">
    Подробнее..
  </button>


  </div>
        <div class="collapse" id="collapseExample">
  <div class="card card-body">
    Скоро здесь будет описание этой настройки.
  </div>
</div>
            </div>


    <div class="card " style="margin-bottom:5px;">

  <div class="card-body d-flex align-items-center " >
      <a class=" btn  shadow-none  h-100 mask btn-block" href="{% url 'home' %}" style="text-align:center; " role="button"> <h3> Сделать уже, убрать границы, сделать стрелочки, вертикальную полосу настроить, шрифт настроить</h3> </a>
       <span class="vertical-line"></span>
      <button class="btn btn-link shadow-none" type="button" data-toggle="collapse" data-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample1" style="text-align:center; ">
    Что это?
  </button>


  </div>
        <div class="collapse" id="collapseExample1">
  <div class="card card-body">
    высота 84 пикселя.
  </div>
</div>
            </div>
</div>






{% endblock %}

botsite/templates/botsite/home.html
{% extends 'botsite/base.html' %}
{% load static %}

{% block Title %}Home{% endblock %}


{% block Content %}

<div class="container main-content">
      {% if user.is_authenticated %}

    <p> Здравствуйте, {{ user.first_name}} {{ user.last_name }}! </p>
    {% endif %}


    <p> Здесь будет о том, что бот умеет и зачем он нужен</p>
</div>
{% endblock %}

botsite/templates/botsite/profile.html
{% extends 'botsite/base.html' %}
{% load static %}

{% block Title %}Profile{% endblock %}
{% block Menu %}
<li class="nav-item active">
    <a class="nav-link mr-1" style="color: #fdfafc !important;" href="{% url 'logout' %}">Выйти</a>

</li>
{% endblock %}

{% block Content %}


<link href="{% static 'botsite/css/profile.css' %}" rel="stylesheet">
<div class="container main-content center-content ">
    <h3 class=" mb-5">Здравствуйте, {{ user.first_name}} {{ user.last_name }}!</h3>


    <div class=" container  mb-4">


        <h6 class=" text-left mb-4">
            <span> Ваши чаты </span></h6>

        {% for conversation in conversations %}
        <div class="card" >
            <div class="card-body" style="padding-bottom: 0rem;">


                    <div class="text-secondaryd-flex h-100 mask  ">
                        <div class="first-content align-self-center  ">
                            <div  class="card-title" >
                                <p>ID: {{conversation.chat_id}}</p> <p>{{conversation.title}}</p>
                            </div>
                        </div>
                    </div>


            </div>
        </div>
        <p></p>
        {% empty %}
        <div class="card">
            <div class="card-body">
                VKBot еще не подключен ни к одному из ваших чатов.
                Как это сделать - читайте по ссылке.

            </div>
        </div>
        {% endfor %}


    </div>


</div>
{% endblock %}

<!--<a  href="#" class="text-decoration-none" >-->
<!-- <a  href="{% url 'conversation_settings' conversation=conversation.peer_id %}" class="text-decoration-none" >-->

botsite/templates/botsite/random_post.html
{% extends 'botsite/base.html' %}
{% load static %}


{% block Title %}Random post{% endblock %}

{% block Content %}


<link href="{% static 'botsite/css/random_post.css' %}" rel="stylesheet">




<div class="container main-content center-content ">
<form action="." method="POST">
    {% csrf_token %}
     {% if chat_setting_form.random_post_group.errors %}{% for error in chat_setting_form.random_post_group.errors %}<p class="error">{{ error }}</p>{% endfor %}{% endif %}
    <label for="id_random_post_group">Группа</label>
    <input type="text" id="id_random_post_group" name="random_post_group"
           class="form-control rounded-pill" value="{{ chat_setting_form.random_post_group.value|default_if_none:'' }}"/>


     <label for="id_random_post_mode">Включить</label>
    <input type="checkbox" id="id_random_post_mode" name="random_post_mode" {% if chat_conversation_form.random_post_mode.value %}checked{% endif %} />


    <p><input type="submit" value="Сохранить"></p>

</form>



</div>

{% endblock %}